export {default as SkillsSection} from './SkillsSection/SkillsSection';
export {default as ProfileInfo} from './ProfileInfo/ProfileInfo';
export {default as ServiceItem} from './ServiceItem/ServiceItem';
export {default as WorkItem} from './WorkItem/WorkItem';
export {default as ContactForm} from './ContactForm/ContactForm';
export {default as ContactInfo} from './ContactInfo/ContactInfo';
export {default as SocialLinks} from './SocialLinks/SocialLinks';
export {default as HeaderLink} from './HeaderLink/HeaderLink';
export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Service} from './Services/Services'
export {default as Work} from './Work/Work'
export {default as Contact} from './Contact/Contact'
export {default as BackToTop} from './BackToTop/BackToTop'